### ISSUE TITLE
Skip install_gems if the repository does not include Gem related information

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1074]
If the repository does not include `Gemfile`, `Gemfile.lock`, `*.gemspec`, and the `gems` section in `sider.yml`, Runners do not have to run `install_gems`. This change improves performance a bit. Also, it would be possible to run Ruby analyses in some environments that have no access to the internet as long as Gem information does not exist in the repository.

**Comment by yykamei** [comment]
We have to consider the `optionals` of the `install_gems`. The following code will try to install `OPTIONAL_GEMS`, which is defined in Runners, when there is no Gem information on users' repositories.

https://github.com/sider/runners/blob/950af192a21fa6b42256d644d65eece51310b8a0/lib/runners/ruby.rb#L14

If I implemented like this, the new Runners don't install optional gems when Gem information does not exist :thinking: 

```diff
diff --git a/lib/runners/ruby.rb b/lib/runners/ruby.rb
index 724c64b..66e3dd7 100644
--- a/lib/runners/ruby.rb
+++ b/lib/runners/ruby.rb
@@ -11,6 +11,8 @@ module Runners
         user_specs = user_specs(user_specs, lockfile)
       end

+      return yield({}) if user_specs.empty?
+
       specs = GemInstaller::Spec.merge(default_specs, user_specs.size > 0 ? user_specs : optionals)

       mktmpdir do |path|
```

**Comment by ybiquitous** [comment]
Good catch! 👍 Then, what about the following requirements not to access RubyGems?

- No `gems:` option in `sider.yml`.
- No `Gemfile` file.
- No `Gemfile.lock` file.
- No `*.gemspec` files.
- No optional gems.

**Comment by yykamei** [comment]
It looks good. I support your suggestion. In this case, the change will be like this; it's very simple.

```diff
diff --git a/lib/runners/ruby.rb b/lib/runners/ruby.rb
index 724c64b..d6a50af 100644
--- a/lib/runners/ruby.rb
+++ b/lib/runners/ruby.rb
@@ -11,6 +11,8 @@ module Runners
         user_specs = user_specs(user_specs, lockfile)
       end

+      return yield({}) if (user_specs + optionals).empty?
+
       specs = GemInstaller::Spec.merge(default_specs, user_specs.size > 0 ? user_specs : optionals)

       mktmpdir do |path|
```

With this change, the following runners will still try to access to RubyGems.

* rubocop
* rails_best_practices
* querly
* haml_lint

**Comment by yykamei** [comment]
I found out [this](https://github.com/sider/runners/issues/1074#issuecomment-627838035) approach will not work because Ruby-related analyzers require `Gemfile` and `Gemfile.lock` in its working directory. These files are generated by `GemInstaller`. I will add `--local` option to `bundle install` when `(user_specs + optionals).empty?` is `true`.

**Comment by ybiquitous** [comment]
`--local` looks correct in this case! 👍
