### ISSUE TITLE
Improve Testing::Smoke and check duplicated tests

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1081]
See [this comment](https://github.com/sider/runners/pull/1080#pullrequestreview-411597066).

> [suggestion] It seems better if checking duplicate tests as follows:
> 
> ```ruby
> s.add_test("foo", ...)
> s.add_test("foo", ...) #=> ArgumentError: duplicate test
> ```
>

**Comment by ybiquitous** [comment]
@yykamei I address this. 💪
