### ISSUE TITLE
Support Cyclomatic Complexity Analyzer

### ISSUE THREAD

**Issue by sumyapp** [sider/runners#1152]
## Information

I want to use Cyclomatic Complexity Analyzer.

For example,
- Website: https://github.com/terryyin/lizard
- Source code: https://github.com/terryyin/lizard
- Language: all languages

**Comment by sumyapp** [comment]
What analysis tool is best? Anyone know that?

**Comment by sumyapp** [comment]
Qualityで使う予定です

**Comment by suetsuguk** [comment]
This issue is duplicated to #1606.
