### ISSUE TITLE
Nokogiri -> REXML

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#125]
Nokogiri is built as a C extension and takes much time on the install.

On the other hand, REXML is written in pure Ruby.
Also, it is maintained in the Ruby organization on GitHub, so it seems to be reliable.

See also:
- https://github.com/sparklemotion/nokogiri
- https://github.com/ruby/rexml

**Comment by ybiquitous** [comment]
For example, Nokogiri is used in our code base like this:

https://github.com/sider/runners/blob/1a293196f083fb0d83900111e57807d939fc0047/lib/runners/processor/phpmd.rb#L126

The main purpose is to parse tools' XML output.

**Comment by yykamei** [comment]
I totally agree :+1:
