### ISSUE TITLE
Support refspecs for merge requests on GitLab

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1395]
The current implementation will add a refspec for pull requests on GitHub here.

https://github.com/sider/runners/blob/5133dee755004c9ee4d4b90cd66f847dd07a21e7/lib/runners/workspace/git.rb#L74-L75

Now, Sider supports GitLab, so we should add a valid refspec for each integration. GitLab's refspec is like `+refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*` according to the [document](https://docs.gitlab.com/ee/user/project/merge_requests/reviewing_and_managing_merge_requests.html#checkout-locally-by-modifying-gitconfig-for-a-given-repository).

Alternatively, it might be sufficient to just add the new refspec. Maybe.

**Comment by yykamei** [comment]
We discussed it about a video meeting and concluded that we will do these:

* [ ] Replace `:pull_number` with `:refspecs` [here](https://github.com/sider/runners/blob/5133dee755004c9ee4d4b90cd66f847dd07a21e7/lib/runners/schema/options.rb#L13)
* [ ] Add additional refspecs from the new parameter `:refspecs`

**Comment by suetsuguk** [comment]
```console
kentaro@debian103amd64:~/depot/test_sideci$ git fetch  --quiet --no-tags --no-recurse-submodules  origin "+refs/heads/*:refs/remotes/origin/*" "+refs/merge-requests/2/head:refs/remotes/merge-requests/2/head"
kentaro@debian103amd64:~/depot/test_sideci$ echo $?
0
kentaro@debian103amd64:~/depot/test_sideci$ git fetch  --quiet --no-tags --no-recurse-submodules  origin "+refs/heads/*:refs/remotes/origin/*" "+refs/pull/2/head:refs/remotes/pull/2/head"
fatal: Couldn't find remote ref refs/pull/2/head
kentaro@debian103amd64:~/depot/test_sideci$ echo $?
128
```

**Comment by yykamei** [comment]
Thank you. Whichever the status is an error or not, I believe https://github.com/sider/runners/issues/1395#issuecomment-675880435 resolves.

**Comment by yykamei** [comment]
I want the next release to contain this change along with #1411. It would be useful to deal with breaking changes at a time.
