### ISSUE TITLE
[Cppcheck] Process aborted or coredumped: #<Process::Status: pid 31 SIGUSR2 (signal 12)>

### ISSUE THREAD

**Issue by suetsuguk** [sider/runners#1458]
According to the log the execution time of the cppcheck process is too long and reaches  the timeout of 30m.

```
...
1795.45s $ cppcheck ...
0.81s    <?xml version="1.0" encoding="UTF-8"?>
0.00s    Process aborted or coredumped: #<Process::Status: pid 31 SIGUSR2 (signal 12)>
...
```

The user has 6190 files in the repository. After reducing target files to 200 with the `ignore` option, the same error still occurs.

**Comment by suetsuguk** [comment]
After discussed with @ybiquitous  and @yykamei , we concluded that we should apply following options to avoid timeout:

- increase the number of CPUs on Docker
- run num-of-CPUs threads of cppcheck #1462
- increase the timeout value #1461

**Comment by ybiquitous** [comment]
@suetsuguk How is your progress?

**Comment by suetsuguk** [comment]
This issue can be closed when the related issue https://github.com/sider/gitlab_sideci/issues/502 is verified.
