### ISSUE TITLE
[stylelint] Consider a new option `--report-descriptionless-disables` introduced in 13.7.0

### ISSUE THREAD

**Issue by suetsuguk** [sider/runners#1476]
This command-line option is added. I don't follow the details so that I have created this issue for further consideration.

```console
$ stylelint --help
...
    --report-descriptionless-disables, --rdd
      Report stylelint-disable comments without a description.
      The process will exit with code 2 if descriptionless disables are found.
...
```

**Comment by yykamei** [comment]
:+1: It's interesting. Perhaps, some users want Sider to show this report, but I'm not sure how to let them know it along with other issues.

**Comment by ybiquitous** [comment]
`--report-descriptionless-disables` has been deprecated since 13.8.0:
https://github.com/stylelint/stylelint/pull/4973
