### ISSUE TITLE
[PMD Java] Support for Java 15 features

### ISSUE THREAD

**Issue by suetsuguk** [sider/runners#1484]
Now PMD 6.27.0 supports for Java 15 features. To enable it we will need to apply changes to our `pmd_java.rb` processor as:
- bundle with OpenJDK 15
- support the `-version` option to specify the language version

Refer to https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.27.0#java-15-support

**Comment by ybiquitous** [comment]
> - bundle with OpenJDK 15

The `openjdk:15.0.2-buster` image has been used already:
https://github.com/sider/devon_rex/blob/2.40.5/java/Dockerfile#L36

> - support the `-version` option to specify the language version

The default value of the `-version` option is `15` already:
https://github.com/pmd/pmd/blob/pmd_releases/6.31.0/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java#L32

Also, in Java, the backward compatibility for source code has been kept, so I think we don't need to add the `version` option.
