### ISSUE TITLE
Improve analyze timeout message

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#1552]
Sider runners have a execution time limitation: 30 minutes. If a running task violate the limitation, we got an error message as below.

```
Process aborted or coredumped: #<Process::Status: pid 29 SIGUSR2 (signal 12)>
```

In my opinion, this is an unfriendly message. Users cannot know that the task has cancelled due to execution time limitation from the message. It is prefer to show `Analyse timeout (30 min.). Please refine your configuration or contact Sider support.`

Note: There is a challenge to use arbitrary message for the timeout. Runners use `timeout` command to limit execution time. This command simply send a SIGUSR2 to the running process. So it is difficult to show 'timeout' message with `timeout`  command.

Related: #1458

**Comment by ybiquitous** [comment]
Thanks for the report! We've used `SIGUSR2` for the timeout.

https://github.com/sider/runners/blob/00118e22b42b8692322bc7193b61d490b6d303aa/images/docker-entrypoint.sh#L39

So, it makes sense to handle `SIGUSR2` specially and improve the error message. 👍 
Maybe, we can just fix the following code to change the error message:

https://github.com/sider/runners/blob/00118e22b42b8692322bc7193b61d490b6d303aa/lib/runners/shell.rb#L119-L123

I think this issue is a bug, not a new feature.

**Comment by ybiquitous** [comment]
[question] Is it possible that the analysis tools exit with `SIGUSR2`, not our timeout?

**Comment by gnakagaw** [comment]
Thanks a lot for your kind reply!

> So, it makes sense to handle SIGUSR2 specially and improve the error message. 👍
> Maybe, we can just fix the following code to change the error message:

It is possible to catch a signaled exit process with `Status#signaled` and `Status#stopsig`. 
https://docs.ruby-lang.org/en/2.7.0/Process/Status.html#method-i-signaled-3F
https://docs.ruby-lang.org/en/2.7.0/Process/Status.html#method-i-stopsig

**Comment by gnakagaw** [comment]
> [question] Is it possible that the analysis tools exit with SIGUSR2, not our timeout?
Technically, yes. But no, actually.

Almost programs running on Linux are terminated with SIGUSR2 because glibc, the de-facto C standard library, [do so that](https://www.gnu.org/software/libc/manual/html_node/Miscellaneous-Signals.html). However, SIGUSR2 is a special process that each application user freely. So it is possible to cancel a termination request technically. But, I guess that almost linter programs don't do that.
