### ISSUE TITLE
Extract the `issue` field from a `result` schema and write issues per each line

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1672]
Recently, our service has got hit the problem of too many issues with Runners—the Runners' result was so large that our service failed to parse it and got killed because of out of memory. I think we don't have to use and show such a big result to our customers, but metadata, such as the total number of issues, is necessary.

I looked into the problem and found out that out of memory happened when parsing each item of JSON sequence. If it's OK for us to use only the total number of issues, I would say we can go on without parsing. However, we want to extract the metadata of Runners' result in this case.

~That's why I want to add a new schema for Trace to show metadata of a result.~

~For example, if the last line contains metadata such as:~

```json
{"result_metadata":{"total_issues":18}}
```

~we can skip the previous lines by consuming the IO stream, and it's sufficient to parse only the last line.~

---

EDIT: We decided to extract `issues` from a `result` schema.

The output by Runners with the new schema is like this:

```json
{"result": {"type": "success", "timestamp": "..."}}
{"issues":{"position":"begin","length":2000}}
{"issue":{...}}
{"issue":{...}}
{"issue":{...}}
{"issue":{...}}
{"issues":{"position":"end","length":2000}}
```

In order to easily get back to the previous format, I want to introduce the new parameter (maybe, an environment variable) `NEW_ISSUE_SCHEMA`.

**Comment by ybiquitous** [comment]
Another solution:

What we want is to know the number of issues before evaluating an array of issues.
So, the following idea seems considerable to me:

- Add `issues_count` to `result`.
- Remove `issues` from `result`.
- Add `result_issues` next to `result`.

```
{"result": { ..., "issues_count": 100 }}
{"result_issues": [...]}
```

---

An example of the current trace:

https://sider.review/gh/repos/202486306/pulls/1619/logs/fa934ddf-e6e5-46bf-95cf-7b0e50ab0f46/raw

<img width="660" alt="image" src="https://user-images.githubusercontent.com/473530/100297971-3b094400-2fd3-11eb-8aaa-97819d020c58.png">

**Comment by yykamei** [comment]
Is it acceptable to change the existing schema? If so, I'll follow your suggestion.

**Comment by ybiquitous** [comment]
I think it's acceptable because we have ever added fields like #1363.

**Comment by yykamei** [comment]
OK. Thanks.

This time, we are going to remove the field `issues` from the `result`. Is it still acceptable? I think users of the Runners must change the means of extracting issues.

**Comment by ybiquitous** [comment]
Who do you assume *users of the Runners*?

**Comment by yykamei** [comment]
I mean a "user" indicates Sider (or sider/sideci). I opened this issue in order to make changes as little as possible, but removing `issues` from `result` seems to require changes on sider/sideci.

**Comment by ybiquitous** [comment]
Yes, we need to change also the logic in Sider by this solution.
The code that can parse both schemas will be required.

**Comment by yykamei** [comment]
See this comment.

https://github.com/sider/runners/pull/1677#issuecomment-734693152
