### ISSUE TITLE
[PHPCS] Add --parallel option

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#1953]
Add `linter.code_sniffer.parallel` option to `sider.yml`

## What is this ?
support [`--parallel` option for phpcs](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#getting-help-from-the-command-line)

## Why?
The options is useful when we analyze a large repository or use a cost-consuming phpcs plugin. Note that this option should be opt-in because parallel processing sometimes causes troubles such as deadlock.

**Comment by ybiquitous** [comment]
@gnakagaw I'm working with the PHPCS options on PR #2132. Can I take also this issue together?

**Comment by ybiquitous** [comment]
I've implemented the `parallel` option via [`d5ad588` (#2132)](https://github.com/sider/runners/pull/2132/commits/d5ad588291c9f1320e8d0e20a83548f4a6f627d9).
