### ISSUE TITLE
Support npm 7

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1963]
npm 7 has beeen `latest` from `next` now.
See <https://twitter.com/npmjs/status/1352357452927393792>.

See also:
- https://docs.npmjs.com/cli/v7/commands/npm-install
- https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
- https://github.blog/2021-02-02-npm-7-is-now-generally-available/
- https://blog.npmjs.org/post/631877012766785536/release-v700

The new version has some **breaking changes**:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/473530/105437176-ebc65380-5ca3-11eb-90e7-73135cd7c21d.png">

Note: We will update the version on devon_rex actually:
https://github.com/sider/devon_rex/blob/f71549a96fe21793d0ff2e612ba81f71207cabaf/npm/package.json#L3

**Comment by ybiquitous** [comment]
In npm 7, `--only=prod` is supported still, but `--only=dev` has been removed.
See <https://docs.npmjs.com/cli/v7/commands/npm-install#omitting-dependency-types>.

So, we should select either way:
- remove the support of `npm_install: development` (show a warning if it is used)
- continue the support of `npm_install: development` in another way
  - E.g. rewriting `package.json` temporarily but quite risky

The `npm_install: development` feature does not seem to be used very often, so I think the former may be good.

**Comment by ybiquitous** [comment]
`npm install` now can read `yarn.lock`. This means we no longer need Yarn.

**Comment by yykamei** [comment]
+1 for <q>remove the support of npm_install: development (show a warning if it is used)</q> :+1:

**Comment by ybiquitous** [comment]
If we would not use Yarn to install packages, users who install private packages via `.yarnrc` might be confused (although such users would be few)... 🤔

**Comment by ybiquitous** [comment]
If considering the case of <https://github.com/sider/runners/issues/1963#issuecomment-791274966>, it might be better to provide the feature #1689 together.
