### ISSUE TITLE
RuboCopUtils#setup_default_rubocop_config should follow user-specified config file

### ISSUE THREAD

**Issue by yykamei** [sider/runners#2018]
`RuboCopUtils#setup_default_rubocop_config` currently checks the existence of `./rubocop.yml` in the `current_dir`, but some users may configure it as an alternative file. So, this method should support such a case. In addition, some linters depend on RuboCop and have their own configuration file (e.g., HAML-Lint takes care of `haml-lint.yml`). I think `#setup_default_rubocop_config` should also consider this case.

https://github.com/sider/runners/blob/00e15ecfcc554084607909759b4cc8f0bfd90a66/lib/runners/rubocop_utils.rb#L66-L74

**Comment by ybiquitous** [comment]
HAML-Lint and Slim-Lint allow users to specify a custom RuboCop config path via the **environment variables**:
- [`HAML_LINT_RUBOCOP_CONF`](https://github.com/sds/haml-lint/blob/6999b4054bc129368d963f4a91d2de886e481ee2/lib/haml_lint/linter/README.md#rubocop)
- [`SLIM_LINT_RUBOCOP_CONF`](https://github.com/sds/slim-lint/blob/a89a91d4e1ffab1c5f054a172f9dbee77df2177e/lib/slim_lint/linter/README.md#rubocop)

But currently, we don't support them, so HAML-Lint and Slim-Lint runners keep the current behavior, that is:
**"The default config is copied if `.rubocop.yml` is not present."**
