### ISSUE TITLE
[Metrics FileInfo] refactoring Metrics FileInfo runner

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2118]
Here is a just list for refactoring..
* supress stdout tracing for `wc -l` 
  * https://github.com/sider/runners/blob/master/lib/runners/processor/metrics_fileinfo.rb#L67
* parallelize `git log -1` calling
  * Process creation is one of special cases that Ruby VM release Global Interpreter Lock (GIL). So, it may be possible to run `git log -1` in parallel.

[EDIT]
I found a bug in `Metrics FileInfo`. We cannot "**/hoge" format in `fnmatch?` function.  https://github.com/sider/runners/blob/master/lib/runners/processor/metrics_fileinfo.rb#L28
ref: https://docs.ruby-lang.org/ja/latest/method/Pathname/i/fnmatch.html

**Comment by ybiquitous** [comment]
Hi @gnakagaw, will you address this issue soon? I can do it if you have no time.

**Comment by gnakagaw** [comment]
@ybiquitous 
I can do the first one (suppressing message) just now. The latter take some time because this is the first time to use thread mechanism of Ruby for me.

**Comment by ybiquitous** [comment]
Using the `parallel` gem is easy to implement:
https://github.com/grosser/parallel

**Comment by gnakagaw** [comment]
@ybiquitous Thx. I'll do it now.

**Comment by ybiquitous** [comment]
We use the gem already here:
https://github.com/sider/runners/blob/c01a76dd3093c5fd037c426715f6438dc1f65022/test/smoke.rb#L77

**Comment by ybiquitous** [comment]
Steps using the `parallel` gem:

1. Move the gem from development to runtime in `runners.gemspec`:
```diff
--- a/runners.gemspec
+++ b/runners.gemspec
@@ -39,12 +39,12 @@ Gem::Specification.new do |spec|
   spec.add_dependency "bugsnag", ">= 6.18"
   spec.add_dependency "git_diff_parser", ">= 3.2"
   spec.add_dependency "jsonseq", ">= 0.2"
+  spec.add_dependency "parallel", ">= 1.20"
   spec.add_dependency "retryable", ">= 3.0"
   spec.add_dependency "strong_json", ">= 2.1"
 
   spec.add_development_dependency "amazing_print"
   spec.add_development_dependency "minitest"
-  spec.add_development_dependency "parallel"
   spec.add_development_dependency "rainbow"
   spec.add_development_dependency "rake"
   spec.add_development_dependency "unification_assertion"
```
2. Run `bundle install`
3. Commit automatically updated `Gemfile.lock` on the step 2
4. Run `bundle exec rbs prototype runtime -r parallel Parallel > sig/parallel.rbs`
5. Commit `sig/parallel.rbs` generated via the step 4

**Comment by gnakagaw** [comment]
@ybiquitous I've completed the implementation. Now, I'm creating a PR..

**Comment by gnakagaw** [comment]
@ybiquitous Ooops. Steep says an error as below. Do you have any idea for that? It seems that we need more type information. (`Parallel::ProcessorCount`)

```
+ │ Diagnostic ID: Ruby::UnexpectedError
+ │
+ └         results = Parallel.map(targets) do |target|
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ sig/parallel.rbs:2:2: [error] Cannot find type `Parallel::ProcessorCount`
+ │ Diagnostic ID: Ruby::UnknownTypeName
+ │
+ └   extend Parallel::ProcessorCount
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ybiquitous** [comment]
Try `bundle exec rbs prototype runtime -r parallel "Parallel::ProcessorCount" >> sig/parallel.rb`

**Comment by gnakagaw** [comment]
@ybiquitous Thx!
