### ISSUE TITLE
Support actionlint

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2601]
## Information

- Website: https://rhysd.github.io/actionlint/
- Source code: https://github.com/rhysd/actionlint
- Language: GitHub Actions

## Why do you need the tool?
[GitHub Actions](https://github.com/features/actions) is a CI/CD platform integrated into GitHub. Users define workflows with [YAML-based DSL](https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions). 

We should provide an analyzer for it because..
* The syntax has complicated specifications.
  * Especially, it is difficult task to write shell scripts in a workflow file.
* Breaking CI/CD configuration has great bad influences to developer experience.
* An Inappropriate CI/CD configuration causes security issues. (e.g. hard-coded credentials, unchecked input processing, etc.)

[actionlint](https://github.com/rhysd/actionlint) could resolve the concerns.

**Comment by ybiquitous** [comment]
The official Docker images are now available!
https://hub.docker.com/r/rhysd/actionlint

**Comment by sumyapp** [comment]
After implementation, wire linter name to here with the beta flag
https://github.com/sider/runners/blob/master/README.md#supported-analyzers

**Comment by sumyapp** [comment]
https://github.com/rhysd/actionlint/blob/main/Dockerfile
maybe useful to implement docker file

**Comment by radomirbosak** [comment]
As a reference: new implementation of other runners added in the past:
* [metrics_complexity](https://github.com/sider/runners/pull/1631)
* [pylint](https://github.com/sider/runners/pull/1149)
