### ISSUE TITLE
[remark-lint] sometimes fails with `git-blame failed: ... The requested URL returned error: 429`

### ISSUE THREAD

**Issue by radomirbosak** [sider/runners#2679]
This is an example log:
```
Run remark-lint
$ remark --report vfile-reporter-json --no-color --no-stdout .
...
exit status: 0
1126 issue(s) found.
Removing issues from unchanged or untracked files...
git-blame failed: fatal: unable to access 'https://github.com/sider/runners.git/': The requested URL returned error: 429
fatal: Cannot read blob 7026d5c03d9fe17d7da746a4c2de9d120791e1a6 for path README.md
 (Runners::Workspace::Git::BlameFailed)
Writing result...
Finish analysis
remark-lint analysis failed.
Finished at 2021-09-14 05:54:28 UTC
Elapsed time: 16s
```

It looks like as if GitHub was contacted during git-blame too many times and returned an error 429: Too many requests

**Comment by dev-yakuza** [comment]
> 1126 issue(s) found.

There are too many errors 🤔

**Comment by ybiquitous** [comment]
This package seems a cause:
https://github.com/davidtheclark/remark-lint-no-dead-urls

**Comment by ybiquitous** [comment]
The `skipUrlPatterns` option seems available.

**Comment by suetsuguk** [comment]
Write the patterns in the `.remarkrc` on the runners project root (not in the remark-preset-lint-sider).

**Comment by ybiquitous** [comment]
This is not a bug. The problem of our remark-lint configuration.
