### ISSUE TITLE
[ESLint] Update dependency (ESLint 8)

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2741]
[ESLint 8 is now available](https://eslint.org/blog/2021/10/eslint-v8.0.0-released). Update dependency of `eslint` runner.
https://github.com/sider/runners/blob/5f6492937012dcb0cd58b88768371dd24668ec1c/lib/runners/processor/eslint.rb#L35

**Comment by radomirbosak** [comment]
Sounds good.

> Another option is removing @vue/eslint-config-typescript from the dependency. But, I don't know whether it is possible or not.

I'm not sure, but it looks like it's a very simple package, it sets only three or four rule defaults for eslint. We may be able to do it by ourselves.
https://github.com/vuejs/eslint-config-typescript/blob/e11179c0dade55484ba631ef5e519ea640526c8e/recommended.js#L10-L22

**Comment by radomirbosak** [comment]
Support for eslint 8.0.0 was added to `@vue/eslint-config-typescript`
https://github.com/vuejs/eslint-config-typescript/releases/tag/v8.0.0

**Comment by radomirbosak** [comment]
Issue for **eslint-plugin-react**: https://github.com/yannickcr/eslint-plugin-react/issues/3055

**Comment by radomirbosak** [comment]
And lastly, **eslint-plugin-react-hooks** published an alpha package with ESLint 8.0.0 support, however didn't release a proper versioned package with *latest* tag. See comment here: https://github.com/facebook/react/pull/22248#issuecomment-940731956

Setting
```json
    "eslint-plugin-react-hooks": "alpha",
```
solves the conflict, but is probably not the best long-term solution.

Relevant npmjs: https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by ybiquitous** [comment]
Is it possible to just change the upper limit as below?

https://github.com/sider/runners/blob/749bc4b4c842d4fb736bf282fe383e5c6c550083/lib/runners/processor/eslint.rb#L35

```diff
- "eslint" => Gem::Requirement.new(">= 5.0.0", "< 8.0.0").freeze,
+ "eslint" => Gem::Requirement.new(">= 5.0.0", "< 9.0.0").freeze,
```

**Comment by gnakagaw** [comment]
@radomirbosak IMO, It's OK to update ESLint dependency not for `eslint` runner but for `sider/runners` repository. What do you think?

**Comment by radomirbosak** [comment]
> Is it possible to just change the upper limit as below?

We could do it, but unless all eslint plugins that we use support ESLint 8.0.0, npm won't bump the version in the lockfile.. 
(if I understand the npm dependency management correctly)

Then it won't make any difference.

Or is there a part of code where ESLint version can be upgraded without conflicting/unsupported dependencies?
I'm a bit confused in situation where we use the same package in different contexts. Which packages are those and can they have different versions in different contexts?

**Comment by ybiquitous** [comment]
The version `CONSTRAINTS` affects only users' packages, not Sider's default packages.
So I suggest:

1. First of all, release a new patch version of Runners with the loosen `CONSTRAINTS` as below:

```diff
- "eslint" => Gem::Requirement.new(">= 5.0.0", "< 8.0.0").freeze,
+ "eslint" => Gem::Requirement.new(">= 5.0.0", "< 9.0.0").freeze,
```

2. Nxt, bump up Sider's default ESLint dependencies when some packages or community prepare for.

**Comment by gnakagaw** [comment]
It seems to be OK. Here is a simple experiment.
```shellsession
$ git diff | cat
diff --git a/lib/runners/processor/eslint.rb b/lib/runners/processor/eslint.rb
index 03c3eda5..84c88865 100644
--- a/lib/runners/processor/eslint.rb
+++ b/lib/runners/processor/eslint.rb
@@ -32,7 +32,7 @@ module Runners
     end

     CONSTRAINTS = {
-      "eslint" => Gem::Requirement.new(">= 5.0.0", "< 8.0.0").freeze,
+      "eslint" => Gem::Requirement.new(">= 5.0.0", "< 9.0.0").freeze,
     }.freeze

     CUSTOM_FORMATTER = (Pathname(Dir.home) / "custom-eslint-json-formatter.js").to_path.freeze
diff --git a/vendor/rbs/gem_rbs_collection b/vendor/rbs/gem_rbs_collection
index 51880bed..55196950 160000
--- a/vendor/rbs/gem_rbs_collection
+++ b/vendor/rbs/gem_rbs_collection
@@ -1 +1 @@
-Subproject commit 51880bed87fbc3dc8076fedb5cf798be05148220
+Subproject commit 551969504a000b3a2f82dc32e4cb3dbc40ea2285
$  bundle exec rake docker:build ANALYZER=eslint
(..skipped..)
$ bundle exec rake docker:smoke ANALYZER=eslint DEBUG=true 2>&1 | grep "will be used"
{"trace":"message","message":"All constraints are not satisfied. The default version `7.32.0` will be used instead.","recorded_at":"2021-11-17T02:23:36.081Z","truncated":false}
{"trace":"message","message":"All constraints are not satisfied. The default version `7.32.0` will be used instead.","recorded_at":"2021-11-17T02:23:36.160Z","truncated":false}
{"trace":"message","message":"All constraints are not satisfied. The default version `7.32.0` will be used instead.","recorded_at":"2021-11-17T02:23:56.897Z","truncated":false}
^C
$
```

**Comment by gnakagaw** [comment]
@ybiquitous The current `CONSTRAINTS` fails analysis for repositories ESLint 8.0 in user's local environment, right?

**Comment by ybiquitous** [comment]
Yes!

**Comment by gnakagaw** [comment]
Thanks. We'll publish a minor release.

**Comment by radomirbosak** [comment]
> The version CONSTRAINTS upper limit affects only users' packages, not Sider's default packages.

Are we talking about the difference in environments that are installed
1. during the container build phase
2. during the linter binary execution phase
?

I forgot that some of the linters install the user package dependencies during their execution.

So the CONSTRAINS are applied during phase 2.

**Comment by gnakagaw** [comment]
> So the CONSTRAINS are applied during phase 2.

Yes. See the code as below.
https://github.com/sider/runners/blob/749bc4b4c842d4fb736bf282fe383e5c6c550083/lib/runners/processor/eslint.rb#L61-L66

**Comment by gnakagaw** [comment]
Now, we can use ESlint `8.x` on `eslint` runner.
![image](https://user-images.githubusercontent.com/48303198/142565708-765332f6-d5a5-497a-b17d-6b8af8cde434.png)

**Comment by radomirbosak** [comment]
As mentioned [here](https://github.com/sider/runners/pull/2742), the last obstacle is that our eslint-plugin-promise plugin still [does not support](https://github.com/xjamundx/eslint-plugin-promise/issues/218) ESLint 8.

However, during a development meeting we talked about possibly not needing many of the plugins that are currently listed as dependencies. If that is the case, we can remove them and upgrade ESLint to version 8.

**Comment by radomirbosak** [comment]
Since this PR https://github.com/sider/runners/pull/2864 is not merged, I think we can close this issue.
