### ISSUE TITLE
Fix CI errors (ESLint)

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2767]
`build (eslint)` CI job have been failed  for repository-wide. Fix it.

e.g.
- https://github.com/sider/runners/runs/3991440783
- https://github.com/sider/runners/runs/3991440168
- https://github.com/sider/runners/runs/3991330525
...

**Comment by gnakagaw** [comment]
related? https://github.com/npm/cli/issues/3666

**Comment by gnakagaw** [comment]
I'll update npm from v7 to v8. 
https://github.com/sider/devon_rex/pull/694

**Comment by radomirbosak** [comment]
Interesting. I always thought the bug is on our side, but I could not figure out where. But it really might be an `npm` bug.

**Comment by radomirbosak** [comment]
I tried updating npm, but it did not help. ESLint test still fails https://github.com/sider/runners/pull/2781

**Comment by gnakagaw** [comment]
This issue will be resolved with next devon_rex update.

**Comment by radomirbosak** [comment]
This was resolved by https://github.com/sider/devon_rex/pull/701 and published in devon_rex 2.46.0 https://github.com/sider/devon_rex/releases/tag/2.46.0
