### ISSUE TITLE
[Metrics Fileinfo] Fix thread unsafe code

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2778]
https://github.com/sider/runners/blob/e4d8efb735b5b1297041b9000c6a859d72be8c3c/lib/runners/processor/metrics_fileinfo.rb#L116-L119

This code assigns a value to a thread unsafe `Hash` in thread context. It was thought to be no problem for two reasons. 1) The hash key is unique between the threads. 2) Thread implementation of CRuby doesn't run thread in parallel (They switch a thread only in I/O operations). However, it brakes a consistency very rarely based on several bug reports.

Rewrite the code to use [`Parallel.map`](https://github.com/grosser/parallel).

**Comment by radomirbosak** [comment]
Alternatively, we could give up on parallel execution altogether.

The `git log` command is not such a slow operation anyway, so it does not matter if it's not executed in parallel.

**Comment by gnakagaw** [comment]
> we could give up on parallel execution altogether.

Some repository contains tons of files. I'd like to preserve the code as possible, but, remove it as the final option.

An simple performance result with parallel processing:
https://github.com/sider/runners/pull/2122#issuecomment-787827046

**Comment by radomirbosak** [comment]
The metrics_fileinfo code for `last_committed_at` was rewritten in https://github.com/sider/runners/pull/2866 and it is no longer thread-unsafe.
