### ISSUE TITLE
Too slow chown -R

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#283]
`chown` on the line below is too slow because it is for all files and directories in the home directory.

https://github.com/sider/runners/blob/dc8f19120d0d9f17d4df22ec0d4985e8575de43d/images/Dockerfile.end.erb#L2

**Comment by yykamei** [comment]
Is [this](https://github.com/docker/for-linux/issues/388) a related issue?
I don't how to solve this problem... I think we have three options:

* Change our code to not require chown(1)
* Try to change the storage driver (Sorry, I'm not sure what driver CircleCI is using)
* Run chown(1) when it's required one by one

**Comment by ybiquitous** [comment]
> Is [this](https://github.com/docker/for-linux/issues/388) a related issue?

I'm not sure, but it is similar. 🙄 

> I don't how to solve this problem... I think we have three options:

Thanks for the suggestion. I think the following option is reasonable:

> Change our code to not require chown(1)
