### ISSUE TITLE
Intrdouce Laravel ruleset for PHP_CodeSniffer

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#300]
See https://github.com/antonioribeiro/laravelcs

See also https://help.sider.review/tools/php/codesniffer

**Comment by ybiquitous** [comment]
Is this reasonable?

**Comment by yykamei** [comment]
It makes sense. I think Laravel is a popular framework in the PHP community.

**Comment by ybiquitous** [comment]
Thank you! We can do this soon. It looks easy to add it.

**Comment by ybiquitous** [comment]
`antonioribeiro/laravelcs` requires `squizlabs/php_codesniffer ~2.0` but we need `squizlabs/php_codesniffer 3.5.0`:

https://github.com/sider/runners/blob/2d1a6e613068aa42539c762a45f8fcaf47ef92e7/images/code_sniffer/composer.json#L3

https://github.com/antonioribeiro/laravelcs/blob/v0.1.0/composer.json#L15
