### ISSUE TITLE
Failed to build SwiftLint

### ISSUE THREAD

**Issue by yykamei** [sider/runners#315]
See https://circleci.com/gh/sider/runners/27334

**Comment by ybiquitous** [comment]
@yykamei Can we use a pre-built version (`portable_swiftlint.zip`) instead of compiling sources?

https://github.com/realm/SwiftLint/releases/tag/0.34.0

**Comment by yykamei** [comment]
No, unfortunately.

I downloaded the file and ran the following command on my Linux laptop.

```shell-session
% unzip portable_swiftlint.zip && ./swiftlint --version
Archive:  portable_swiftlint.zip
  inflating: swiftlint
  inflating: LICENSE
zsh: exec format error: ./swiftlint
```

From this result, `portable_swiftlint.zip` is a binary for macOS.

**Comment by ybiquitous** [comment]
Related? https://github.com/realm/SwiftLint/issues/2905

**Comment by yykamei** [comment]
I think so! Thank you.
But, the next release of SwiftLint will drop the support of Swift 4.2.x. Perhaps, we have to apply the patch ourselves...

**Comment by ybiquitous** [comment]
Hum..., it seems that we should prepare migration steps from Swift 4 to Swift 5.

Anyway, is there a way to avoid the current CI failure?

**Comment by ybiquitous** [comment]
`git submodule update --init` seems to be the main cause. Is there a way to avoid it?

**Comment by ybiquitous** [comment]
I resolved this by adding a patch in Dockerfile. I'll open a PR. 💪
