### ISSUE TITLE
Introduce a hierarchy of error classes

### ISSUE THREAD

**Issue by yykamei** [sider/runners#506]
The suggestion is out of the scope of this PR, but it seems good that we will introduce a hierarchy of error classes as follow:

```ruby
# lib/runners/errors.rb
module Runners
  class Error < StandardError; end
  class UserError < Error; end
  class SystemError < Error; end
end
```

By doing this, we will not refer to concrete error classes:

```diff
-rescue Runners::Processor::CIConfigBroken => exn
+rescue UserError => exn
```

_Originally posted by @ybiquitous in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM0Nzc0ODUxNQ==/comments/review_comment_

**Comment by ybiquitous** [comment]
We will need a custom rule to disallow `class Foo < StandardError`.
