### ISSUE TITLE
Rename NodeHarness namespace to something else?

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#59]
Because we may be confusing... 🤔 

https://github.com/sider/runners/blob/770c6e06010fc8a19f218178252b8ccf6923d34d/lib/node_harness.rb#L86

**Comment by yykamei** [comment]
I agree, but I have no ideas :sweat_smile:

**Comment by ybiquitous** [comment]
`Sider::Runners`?

**Comment by ybiquitous** [comment]
Or just `Runners`?

**Comment by yykamei** [comment]
`Harness` is good to me, but the current implementation already uses `Harness` as a class.

`Runners::Runners::RuboCop` or `Sider::Runners::Runners::RuboCop` is weird...

**Comment by ybiquitous** [comment]
Sure, let's keep the issue as is until we will get some good ideas...

**Comment by ybiquitous** [comment]
One idea: `Runners::Processor::RuboCop`, `Runners::Processor::Eslint`, ...

**Comment by yykamei** [comment]
`Runners::Processor::RuboCop` seems good :+1: I didn't get the idea.
