### ISSUE TITLE
Drop Python 2 support 2020/10E

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#603]
Python 2 will stop the update on January 1, 2020.

https://github.com/sider/runners/blob/04034b07bda2ee5ee33d744be9556f2bc3466715/lib/runners/processor/flake8.rb#L64-L71

[Python 2.7 Countdown](https://pythonclock.org/)

**Comment by ybiquitous** [comment]
See also #607 and https://github.com/sider/devon_rex/issues/161

**Comment by sumyapp** [comment]
- [ ] Announce this information to Sider customers in May. We will drop the support end of June.

**Comment by yykamei** [comment]
https://github.com/sider/devon_rex/issues/161 relates to this issue. We haven't yet announced, so it might be good to postpone.

**Comment by yykamei** [comment]
We are now ready to address this issue at the end of October 2020.

https://blog.sideci.com/drop-the-support-for-python-2-at-the-end-of-october-2020-68d2748545c9
