### ISSUE TITLE
The strict gemspec file causes an error of analyses

### ISSUE THREAD

**Issue by yykamei** [sider/runners#652]
If the target repository contains a gemspec file which requires Bundler dependency, some analyses will fail because of its strict dependency.

```ruby
spec.add_development_dependency "bundler", "~> 2.0.0"
```

In this gemspec file, we should use Bundler 2.0.x, but our current Runners use Bundler 2.1.x, so analyses will fail.

> Maybe. We might have to install Bundler `2.1.x`, `2.0.x`, and `1.x` in case we can handle the various gemspec files.

_Originally posted by @yykamei in https://github.com/sider/runners/pull/646/review_comment/create_

**Comment by ybiquitous** [comment]
Ideally, I think our Bundler version should not affect on Bundler version in user's Gemfiles.

**Comment by ybiquitous** [comment]
@yykamei How many analyses do you think caused by this error?

If fewer, I think the error is rather good because the error can promote the Bundler update.

Also, in some cases, it seems there no failures. I'll show such cases.

**Comment by yykamei** [comment]
I believe there are few repositories that include such a strict gemspec file. I agree with you that we should show an error.

**Comment by ybiquitous** [comment]
Runners has already shown the error. See #875.
