### ISSUE TITLE
Whole `sider.yml` schema check

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#750]
I believe that we need a schema check for the whole `sider.yml`.

Currently, each `linters.*` schema check is just supported. This cannot check the following `sider.yml`:

```yaml
linters:
  rubocop:
    gems:
      - rubocop-rails
  unknown: |
    What is this?
```

Next actions:

* [x] Pass `config` to `Processor#initialize` from `Harness`
* [x] Use `config` in brakeman
* [x] Use `config` in checkstyle
* [x] Use `config` in code_sniffer
* [x] Use `config` in coffeelint
* [x] Use `config` in cppcheck
* [x] Use `config` in cpplint
* [x] Use `config` in eslint
* [x] Use `config` in flake8
* [x] Use `config` in fxcop
* [x] Use `config` in go_vet
* [x] Use `config` in golangci_lint
* [x] Use `config` in golint
* [x] Use `config` in gometalinter
* [x] Use `config` in goodcheck
* [x] Use `config` in hadolint
* [x] Use `config` in haml_lint
* [x] Use `config` in javasee
* [x] Use `config` in jshint
* [x] Use `config` in ktlint
* [x] Use `config` in misspell
* [x] Use `config` in phinder
* [x] Use `config` in phpmd
* [x] Use `config` in pmd_java
* [x] Use `config` in querly
* [x] Use `config` in rails_best_practices
* [x] Use `config` in reek
* [x] Use `config` in rubocop
* [x] Use `config` in scss_lint
* [x] Use `config` in shellcheck
* [x] Use `config` in stylelint
* [x] Use `config` in swiftlint
* [x] Use `config` in tslint
* [x] Use `config` in tyscan

**Comment by yykamei** [comment]
I need this issue to be resolved because of #760. What plan do you have?
If you don't get into this issue, I want to implement it.

My plan is to create `Config` class in `config.rb` and instantiate it in `Harness`.  Then, I want to pass the instance to a processor.

**Comment by yykamei** [comment]
The reason I will instantiate `Config` in `Harness` is that `Harness` can raise `Results::Failure`. If `sider.yml` is broken, we should return `Failure`.

**Comment by ybiquitous** [comment]
I've no plan now. Let's go as you want! 💪

**Comment by yykamei** [comment]
I edited the description for the next steps.

**Comment by yykamei** [comment]
I believe we can close this issue via #763, #777, #779, and #782.
