### ISSUE TITLE
Rename `ci_config_section_name` to `analyzer_id`.

### ISSUE THREAD

**Issue by yykamei** [sider/runners#786]
The name `ci_config_section_name` is not appropriate because Sider is not a CI.
I want to change the method with `analyzer_id`.
Also, I can use the new method `analyzer_id` in the file below:

https://github.com/sider/runners/blob/09f9e08516d053b006eff0cb6e3581810a1696eb/lib/runners/cli.rb#L34-L38

This is the newer version that uses `analyzer_id`.

```ruby
def processor_class
  @processor_class ||= (Processor.subclasses.detect do |cls|
    analyzer == cls.analyzer_id
  end or raise "Not found processor class with '#{analyzer}'")
end
```

_Originally posted by @yykamei in https://github.com/sider/runners/pull/763#issuecomment-592442055_

**Comment by ybiquitous** [comment]
@yykamei Can I do this issue? Are you woring on this issue?

**Comment by yykamei** [comment]
You can do it! I'm not doing it...
