### ISSUE TITLE
Support PMD CPD

### ISSUE THREAD

**Issue by sumyapp** [sider/runners#812]
## Information

- Website: https://pmd.github.io/latest/pmd_userdocs_cpd.html
- Source code: https://github.com/pmd/pmd
- Language: Many. See the [supported languages](https://pmd.github.io/latest/pmd_userdocs_cpd.html#supported-languages)

## Why do you need the tool?

Any CPD (Copy Paste Detector) tools have not been supported.

## Additional context

None.

## See also

None.

**Comment by ybiquitous** [comment]
The same Docker image as PMD Java seems available:
https://github.com/sider/runners/tree/master/images/pmd_java
