### ISSUE TITLE
Tool slow unit tests

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#841]
Currently, `rake test` takes about 3m 30s. See the [CI log](https://github.com/sider/runners/runs/497115016#step:5:1).

Perhaps I think `RubyTest` may be the slowest. I want to improve the time.

https://github.com/sider/runners/blob/43c96c8f3c19295faf0ea9f07d67faee71d60463/test/ruby_test.rb#L3

**Comment by ybiquitous** [comment]
Here is a result on my local machine. The accesses to the mirror `https://rubygems.cae.me.uk` makes slow...

```
$ bundle exec ruby -Itest test/ruby_test.rb -v
Run options: -v --seed 25146

# Running:

RubyTest#test_ensure_lockfile_with_conflict_gemfile_lock = 0.00 s = .
RubyTest#test_install_gems_with_only_other_rubygems = 32.48 s = .
RubyTest#test_ensure_lockfile_with_gemfile_lock = 15.44 s = .
RubyTest#test_install_failure = 1.68 s = .
RubyTest#test_ensure_lockfile_with_gemspec = 1.97 s = .
RubyTest#test_from_gems = 0.00 s = .
RubyTest#test_install_gems_with_optionals = 6.59 s = .
RubyTest#test_install_gems_with_only_git_sources = 15.34 s = .
RubyTest#test_install_no_gems = 2.07 s = .
RubyTest#test_default_gem_specs = 0.00 s = .
RubyTest#test_no_install = 1.02 s = .
RubyTest#test_ensure_lockfile_with_invalid_gemfile_only = 0.31 s = .
RubyTest#test_installed_gem_versions = 0.00 s = .
RubyTest#test_merge_specs = 0.00 s = .
RubyTest#test_install_gems_with_gems_failure = 0.34 s = .
RubyTest#test_gemfile_content_without_default_gems = 0.00 s = .
RubyTest#test_install_gems_with_other_sources = 66.33 s = .
RubyTest#test_install_success = 9.22 s = .
RubyTest#test_install_gems_with_git_sources = 84.72 s = .
RubyTest#test_install_gems_with_gemfile_lock = 14.14 s = .
RubyTest#test_ensure_lockfile_with_gemfile_lock_generated_by_bundler_v1 = 0.00 s = .
RubyTest#test_install_gems_with_gems_which_does_not_satisfy_constraints = 2.12 s = .
RubyTest#test_gemfile_content = 0.00 s = .
RubyTest#test_install_gems_with_gemfile_lock_which_does_not_satisfy_constraints = 7.18 s = .
RubyTest#test_install_gems_with_gems = 7.33 s = .
RubyTest#test_ensure_lockfile_without_gemfile_lock = 1.85 s = .

Finished in 270.153874s, 0.0962 runs/s, 0.3331 assertions/s.

26 runs, 90 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by yykamei** [comment]
Yes, it does. As far as I know, there are no alternative mirrors of RubyGems.org, aside from `rubygems.cae.me.uk`. Building our own RubyGems mirror might improve the speed of testing, but maintaining the mirror service is cumbersome to me.

Another option: just delete the test....

**Comment by ybiquitous** [comment]
> there are no alternative mirrors of RubyGems.org, aside from `rubygems.cae.me.uk`.

Surely... https://github.com/rubygems/rubygems-mirror/wiki/Known-mirrors

**Comment by ybiquitous** [comment]
> RubyTest#test_install_gems_with_git_sources = 84.72 s

not using the mirror 👀 

https://github.com/sider/runners/blob/b81ff40efb74dae439c294b27681fca1efdad6ed/test/ruby_test.rb#L695

**Comment by yykamei** [comment]
+1 for skipping the test

**Comment by ybiquitous** [comment]
I think it a not good idea to skip or remove the slow test, because smoke tests do not ensure all test cases about gem installation.

I'm thinking about how to speed up as possible, keeping the existing test cases. 🤔 
If we cannot speed up, it seems better to keep as-is. Because smoke tests are slower on the CI.
The slow time is a problem only when running tests on our local machine.

**Comment by yykamei** [comment]
OK, you're right.

**Comment by ybiquitous** [comment]
One solution is to start a local gem server. See <https://guides.rubygems.org/run-your-own-gem-server/>

But the test code would be more complex...
