### ISSUE TITLE
Fix "Argument list too long" error generated with git(1)

### ISSUE THREAD

**Issue by yykamei** [sider/runners#935]
I guess this error is attributed to this line.

https://github.com/sider/runners/blob/1ff6d9d89c49539f3547eb94fe114475d984484d/lib/runners/ignoring.rb#L42

I think xargs(1) helps us.

**Comment by yykamei** [comment]
I'm considering the following steps:

1. Create `Runners::Shell#pipeline`, which is like [`Open3.pipeline`](https://ruby-doc.org/stdlib-2.7.1/libdoc/open3/rdoc/Open3.html#method-c-pipeline)
2. Use `Runners::Shell#pipeline` like this: `shell.pipeline(["cat", "/tmp/ignore-files.txt"], ["git", "check-ignore", "--stdin"])

However, just for this error, it would be overdeveloping to create `Runners::Shell#pipeline`.
Using a pipe `|` in `capture3` might be sufficient. What do you think? @ybiquitous

**Comment by ybiquitous** [comment]
In this case, I think that the OS command injection is never raised, so using `capture3` seems good. 👍 

```ruby
capture3!("cat files.txt | git check-ignore --stding", ...)
```

**Comment by ybiquitous** [comment]
But if using `|`,  pipe failed error is handled correctly?

**Comment by ybiquitous** [comment]
Perhaps, `opts[:stdin_data`] may be available?

https://ruby-doc.org/stdlib-2.7.1/libdoc/open3/rdoc/Open3.html#method-c-capture3

**Comment by ybiquitous** [comment]
E.g.

```ruby
capture3!("git check-ignore --stdin", stdin_data: File.read("files.txt"))
```

**Comment by yykamei** [comment]
> ```ruby
> capture3!("git check-ignore --stdin", stdin_data: File.read("files.txt"))
> ```

This is better. Thank you.
