### ISSUE TITLE
"No space left on device" error on Git workspace

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#951]
>  Errno::ENOSPC · No space left on device - copy_file_range 

https://github.com/sider/runners/blob/eb710073dbb23a51c29200e76fc96274a8cf3741/lib/runners/workspace/git.rb#L24-L29

**Comment by ybiquitous** [comment]
I will try to use the git checkout directory as the working directory.

**Comment by yykamei** [comment]
It must be a good idea.

**Comment by ybiquitous** [comment]
Should `Workspace::Git` have two working directory (base and head)...? 🤔

**Comment by ybiquitous** [comment]
It seems that we can simplify `Changes.calculate()` for Git workspace:

https://github.com/sider/runners/blob/fdaf9b95af8d3b2eee0a5e60e2e5064a14b9e40c/lib/runners/changes.rb#L49

For example, `git diff --stat 953c5e7a...HEAD` can get changed files. 🤔

**Comment by yykamei** [comment]
For `Workspace::HTTP`, the self-implemented `calculate` seems necessary. Of course, only with `Workspace::Git`, git-diff(1) completely satisfies our needs.
