### ISSUE TITLE
Refactor Testing::Smoke

### ISSUE THREAD

**Issue by yykamei** [sider/runners#983]
I want to refactor this class with the following things:

* Use [bind mounts](https://docs.docker.com/storage/bind-mounts/)
    - It's a little complicated for me to use [`--volumes-from`](https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container---volumes-from)
    - However, I'm not sure if we can use Bind mounts on GitHub Actions
* Remove unused [`Configuration`](https://github.com/sider/runners/blob/0c120811f4f2102edf2954030ebb9ee9741c5688/lib/runners/testing/smoke.rb#L18) and [`configs`](https://github.com/sider/runners/blob/0c120811f4f2102edf2954030ebb9ee9741c5688/lib/runners/testing/smoke.rb#L172)

**Comment by ybiquitous** [comment]
Totally agreed! 👍

**Comment by ybiquitous** [comment]
FYI.

- https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
- https://github.com/actions/runner/blob/master/docs/start/envlinux.md

**Comment by ybiquitous** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/473530/79818060-d3967080-83c1-11ea-9d05-5eb49644f3ef.png">
