### ISSUE TITLE
Support clang-tidy

### ISSUE THREAD

**Issue by suetsuguk** [sider/runners#996]
## Information

- Website: https://clang.llvm.org/extra/clang-tidy/
- Source code: https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clang-tidy/cppcoreguidelines/
- Language: C++

## Why do you need the tool?

The development members of our company mainly use C++ for our products.
The Core Guidelines provided by Standard C++ Foundation will help them to use modern C++ effectively.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

## Additional context

There are two possible candidates of the Core Guidelines implementation.

- clang-tidy
- Visual Studio built-in checker https://docs.microsoft.com/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=vs-2019

**Comment by ybiquitous** [comment]
Sounds interesting. Could you please describe the difference from [cpplint](https://github.com/cpplint/cpplint) and [cppcheck](https://github.com/danmar/cppcheck)?

**Comment by suetsuguk** [comment]
Here is the pros and cons of clang-tidy. It is rather a static analysis tool than a linter.

pros
- Provides suggested code changes in addition to help messages.
- Covers more than twenty coding conventions including the Google's style guide.

cons
- Requires compiling and all the build dependency.

**Comment by ybiquitous** [comment]
> * Covers more than twenty coding conventions including the Google's style guide.

Cpplint covers the Google's style guide but is there are something differeces?

<img width="951" alt="image" src="https://user-images.githubusercontent.com/473530/80081345-c9c16880-858d-11ea-8511-b3d6a64fe20f.png">

**Comment by ybiquitous** [comment]
Oh, clang-tidy looks useful for users who don't use Google style guide. 👍 

> * Requires compiling and all the build dependency.

For each project?

**Comment by suetsuguk** [comment]
Yes, it seems that clang-tidy invokes the Clang compiler frontend with the target project, and analyses the intermediate representation of a program source code.

**Comment by suetsuguk** [comment]
> * Requires compiling and all the build dependency.

Clang-tidy requires only compiling, though the build dependency is not needed.
We can invoke the clang-tidy with a single source-code file as a command-line argument.
We also need to specify the complete paths of all include files with the command line after '-- -I' or the compile_commands.json file generated by CMake.
- https://clang.llvm.org/extra/clang-tidy/
- https://clang.llvm.org/docs/HowToSetupToolingForLLVM.html

**Comment by yykamei** [comment]
Interesting. All clang-tidy needs seem to be a "compile command database." It would be a simple way to create the `compile_commands.json` with CMake. I'm not sure we can always run cmake(1) for any repositories, though.

**Comment by suetsuguk** [comment]
We have two issues to solve.
1. How to allow users to deploy development packages on the runner instance
2. How to allow users to specify "include paths"

As for 1, a possible solution is to let users to specify a list of packages to deploy, e.g:
```yaml
sider.yml

clang-tidy:
  packages:
    - libboost-all-dev
    - libz3-dev=4.4.1-1~deb10u1
```

Now that we user the Docker `debian:buster` image as our base image, we accept only debian packages. This might cause an inconvenience for users of other OS.
Worse than that, this could be quite useless for Windows users.

As for 2, there are two solutions: A. run cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, B. let users to specify "incldue paths".

- A. run cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

If users adopt CMake as their build environment, we can easily run the Clang-Tidy. The command-line goes to like this;

```shell
$ cd prj_dir
$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B mybuild # this generates compiler_commands.json on the mybuild directory
$ run-clang-tidy -p mybuild
```

Visual Studio (not VSCode) seems to apply this approach. See https://docs.microsoft.com/ja-jp/cpp/code-quality/clang-tidy?view=vs-2019

CMake is getting popular. Indeed, Mr. M of our company applies CMake to his projects. He could be a candidate for the beta-tester of this analyzer.

The following concerned scenario can occur.

The cmake command will report missing packages (see below). Users can notice missing packages from the console log on the SideCI, so that they can add remaining packages to the `clang-tidy: packages:` list in the sider.yml.

```shell
$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B mybuild
CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:1357 (file):
  file STRINGS file "/usr/include/boost/version.hpp" cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:86 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_chrono
          boost_system
          boost_timer

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:86 (FIND_PACKAGE)
```

- B. let users to specify "include paths"

We provides a `includes` variable so that users can specify paths that contain their own header files (.h).
This is because Clang-tidy searches header files defined in the source file (#include "foo") and compile them.

```yaml
sider.yml

clang-tidy:
  packages:
    - libboost-all-dev
  includes:
    - myinclude
```

The pseudo analyze code goes to like this:

```
for file in glob("*.c[pp]"):
  stdout = capture3("clang-tidy", "--", "-I", *config[:includes])
  issues.add(parse_result(stdout))
```

A VSCode plugin applies this approach. See https://github.com/alesiong/clang-tidy-linter/


The following concerned scenario can occur.

If a user was forgetting to add include path to the `clang-tidy: includes:` list, clang-tidy reports an error as;

```shell
$ clang-tidy example/boost/msgpack_variant_capitalize.cpp
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "example/boost/msgpack_variant_capitalize.cpp"
No compilation database found in /home/kentaro/depot/msgpack-c/example/boost or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
1 error generated.
Error while processing /home/kentaro/depot/msgpack-c/example/boost/msgpack_variant_capitalize.cpp.
/home/kentaro/depot/msgpack-c/example/boost/msgpack_variant_capitalize.cpp:16:10: error: 'msgpack.hpp' file not found [clang-diagnostic-error]
#include <msgpack.hpp>
         ^
Found compiler error(s).
```

On the console log of SideCI, users can notice missing include path. Re-run the analysis after adding the include path to the sider.yml, then we get;

```
$ clang-tidy example/boost/msgpack_variant_capitalize.cpp  -- -I include/
1 error generated.
Error while processing /home/kentaro/depot/msgpack-c/example/boost/msgpack_variant_capitalize.cpp.
include/msgpack/sysdep.hpp:91:10: error: 'boost/predef/other/endian.h' file not found [clang-diagnostic-error]
#include <boost/predef/other/endian.h>
         ^
Found compiler error(s).
```

This time, we realize that the boost C/C++ library is not installed on the system. Re-run after adding the package to the sider.yml, then we finally get the clang-tidy results.

**Comment by suetsuguk** [comment]
I also noticed the following concerns.
- From a security point of view, we do not want to allow users to install any package via the `clang-tidy: packages:` list in sider.yml.
- In some projects, users write `find_package()` in a CMakeLists.txt to check if a development tool (e.g. Lex, Yacc) is installed on the system. If any dependent tool is not found, CMake command reports an error.

To handle the conflicting conditions above, we can not adopt CMake for our clang-tidy analyzer. Alternative solution is as follows:
- a package name starting with `lib` is applicable to the `clang-tidy: packages:` list.
- adopt `B. let users to specify "include paths"` instead of CMake

**Comment by suetsuguk** [comment]
Additionally consider the following during coding the analyzer.
- The analyzer needs to get root privileges to install packages.
- Consider the command injection attack. Test a package name with a semicolon and another command like this `packages: "sl;echo hello"`

**Comment by ybiquitous** [comment]
My suggestion:

```yaml
# sider.yml
linter:
  clang-tidy:
    system-packages: # default `os` is `debian`
      - libz3-dev
  cppcheck:
    system-packages:
      os: windows
      packages:
        - libz3-dev
```
